### ISSUE TITLE
minifyする方法が不明のため、CSSやJavaScriptに対する修正のMR作成が困難

### ISSUE THREAD

**Issue by tom-konda** [mug-jp/maplibre-gl-opacity#3]
現状、ライブラリのpackage.jsonにCSSとJavaScriptのminifyを行う`devDependencies`と`npm scripts`が定義されていません。
第三者からCSSやJavaScriptのminifyファイルまでの修正をMRで出すことが困難に思えます。
今後、minifyをする方法の実装予定はありますか。

**Comment by dayjournal** [comment]
This pull request merge allows minify. 
Thank you for your contribution! @Kta-M
https://github.com/mug-jp/maplibre-gl-opacity/pull/4
